channels:
  - conda-forge
  - defaults
  - pyviz
dependencies:
  - jupyterlab
  - jupyter
  - mamba
  - hyperspy
  - pandas
  - numpy
  - matplotlib
  - dask-jobqueue
  - nodejs
  - pip
  - selenium
  - geckodriver
  - firefox
  - numba
  - lmfit
  - ipympl
  - ipykernel
  - ipywidgets
  - dask-labextension
  - mpi4py
  - h5netcdf
  - panel
  - bokeh
  - xarray
  - hvplot
  - bokeh
  - dask
  - datashader
  - colorcet
  - netCDF4
  - bottleneck
  - plotly
  - jupyter_bokeh
  - elm
  - pip:
      - renishawWiRE
      - PyQt5
      - sklearn_xarray
      - sklearn-xarray
      - numdifftools
